package com.echair.project_manage.dao.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AlphaExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table version_alpha
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table version_alpha
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table version_alpha
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_alpha
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public AlphaExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_alpha
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_alpha
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_alpha
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_alpha
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_alpha
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_alpha
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_alpha
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_alpha
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_alpha
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_alpha
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table version_alpha
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andVaersionIsNull() {
            addCriterion("vaersion is null");
            return (Criteria) this;
        }

        public Criteria andVaersionIsNotNull() {
            addCriterion("vaersion is not null");
            return (Criteria) this;
        }

        public Criteria andVaersionEqualTo(String value) {
            addCriterion("vaersion =", value, "vaersion");
            return (Criteria) this;
        }

        public Criteria andVaersionNotEqualTo(String value) {
            addCriterion("vaersion <>", value, "vaersion");
            return (Criteria) this;
        }

        public Criteria andVaersionGreaterThan(String value) {
            addCriterion("vaersion >", value, "vaersion");
            return (Criteria) this;
        }

        public Criteria andVaersionGreaterThanOrEqualTo(String value) {
            addCriterion("vaersion >=", value, "vaersion");
            return (Criteria) this;
        }

        public Criteria andVaersionLessThan(String value) {
            addCriterion("vaersion <", value, "vaersion");
            return (Criteria) this;
        }

        public Criteria andVaersionLessThanOrEqualTo(String value) {
            addCriterion("vaersion <=", value, "vaersion");
            return (Criteria) this;
        }

        public Criteria andVaersionLike(String value) {
            addCriterion("vaersion like", value, "vaersion");
            return (Criteria) this;
        }

        public Criteria andVaersionNotLike(String value) {
            addCriterion("vaersion not like", value, "vaersion");
            return (Criteria) this;
        }

        public Criteria andVaersionIn(List<String> values) {
            addCriterion("vaersion in", values, "vaersion");
            return (Criteria) this;
        }

        public Criteria andVaersionNotIn(List<String> values) {
            addCriterion("vaersion not in", values, "vaersion");
            return (Criteria) this;
        }

        public Criteria andVaersionBetween(String value1, String value2) {
            addCriterion("vaersion between", value1, value2, "vaersion");
            return (Criteria) this;
        }

        public Criteria andVaersionNotBetween(String value1, String value2) {
            addCriterion("vaersion not between", value1, value2, "vaersion");
            return (Criteria) this;
        }

        public Criteria andVaersionIdIsNull() {
            addCriterion("vaersion_id is null");
            return (Criteria) this;
        }

        public Criteria andVaersionIdIsNotNull() {
            addCriterion("vaersion_id is not null");
            return (Criteria) this;
        }

        public Criteria andVaersionIdEqualTo(Integer value) {
            addCriterion("vaersion_id =", value, "vaersionId");
            return (Criteria) this;
        }

        public Criteria andVaersionIdNotEqualTo(Integer value) {
            addCriterion("vaersion_id <>", value, "vaersionId");
            return (Criteria) this;
        }

        public Criteria andVaersionIdGreaterThan(Integer value) {
            addCriterion("vaersion_id >", value, "vaersionId");
            return (Criteria) this;
        }

        public Criteria andVaersionIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("vaersion_id >=", value, "vaersionId");
            return (Criteria) this;
        }

        public Criteria andVaersionIdLessThan(Integer value) {
            addCriterion("vaersion_id <", value, "vaersionId");
            return (Criteria) this;
        }

        public Criteria andVaersionIdLessThanOrEqualTo(Integer value) {
            addCriterion("vaersion_id <=", value, "vaersionId");
            return (Criteria) this;
        }

        public Criteria andVaersionIdIn(List<Integer> values) {
            addCriterion("vaersion_id in", values, "vaersionId");
            return (Criteria) this;
        }

        public Criteria andVaersionIdNotIn(List<Integer> values) {
            addCriterion("vaersion_id not in", values, "vaersionId");
            return (Criteria) this;
        }

        public Criteria andVaersionIdBetween(Integer value1, Integer value2) {
            addCriterion("vaersion_id between", value1, value2, "vaersionId");
            return (Criteria) this;
        }

        public Criteria andVaersionIdNotBetween(Integer value1, Integer value2) {
            addCriterion("vaersion_id not between", value1, value2, "vaersionId");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNull() {
            addCriterion("project_id is null");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNotNull() {
            addCriterion("project_id is not null");
            return (Criteria) this;
        }

        public Criteria andProjectIdEqualTo(Long value) {
            addCriterion("project_id =", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotEqualTo(Long value) {
            addCriterion("project_id <>", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThan(Long value) {
            addCriterion("project_id >", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThanOrEqualTo(Long value) {
            addCriterion("project_id >=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThan(Long value) {
            addCriterion("project_id <", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThanOrEqualTo(Long value) {
            addCriterion("project_id <=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdIn(List<Long> values) {
            addCriterion("project_id in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotIn(List<Long> values) {
            addCriterion("project_id not in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdBetween(Long value1, Long value2) {
            addCriterion("project_id between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotBetween(Long value1, Long value2) {
            addCriterion("project_id not between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andFrontUeIsNull() {
            addCriterion("front_ue is null");
            return (Criteria) this;
        }

        public Criteria andFrontUeIsNotNull() {
            addCriterion("front_ue is not null");
            return (Criteria) this;
        }

        public Criteria andFrontUeEqualTo(String value) {
            addCriterion("front_ue =", value, "frontUe");
            return (Criteria) this;
        }

        public Criteria andFrontUeNotEqualTo(String value) {
            addCriterion("front_ue <>", value, "frontUe");
            return (Criteria) this;
        }

        public Criteria andFrontUeGreaterThan(String value) {
            addCriterion("front_ue >", value, "frontUe");
            return (Criteria) this;
        }

        public Criteria andFrontUeGreaterThanOrEqualTo(String value) {
            addCriterion("front_ue >=", value, "frontUe");
            return (Criteria) this;
        }

        public Criteria andFrontUeLessThan(String value) {
            addCriterion("front_ue <", value, "frontUe");
            return (Criteria) this;
        }

        public Criteria andFrontUeLessThanOrEqualTo(String value) {
            addCriterion("front_ue <=", value, "frontUe");
            return (Criteria) this;
        }

        public Criteria andFrontUeLike(String value) {
            addCriterion("front_ue like", value, "frontUe");
            return (Criteria) this;
        }

        public Criteria andFrontUeNotLike(String value) {
            addCriterion("front_ue not like", value, "frontUe");
            return (Criteria) this;
        }

        public Criteria andFrontUeIn(List<String> values) {
            addCriterion("front_ue in", values, "frontUe");
            return (Criteria) this;
        }

        public Criteria andFrontUeNotIn(List<String> values) {
            addCriterion("front_ue not in", values, "frontUe");
            return (Criteria) this;
        }

        public Criteria andFrontUeBetween(String value1, String value2) {
            addCriterion("front_ue between", value1, value2, "frontUe");
            return (Criteria) this;
        }

        public Criteria andFrontUeNotBetween(String value1, String value2) {
            addCriterion("front_ue not between", value1, value2, "frontUe");
            return (Criteria) this;
        }

        public Criteria andFrontUiIsNull() {
            addCriterion("front_ui is null");
            return (Criteria) this;
        }

        public Criteria andFrontUiIsNotNull() {
            addCriterion("front_ui is not null");
            return (Criteria) this;
        }

        public Criteria andFrontUiEqualTo(String value) {
            addCriterion("front_ui =", value, "frontUi");
            return (Criteria) this;
        }

        public Criteria andFrontUiNotEqualTo(String value) {
            addCriterion("front_ui <>", value, "frontUi");
            return (Criteria) this;
        }

        public Criteria andFrontUiGreaterThan(String value) {
            addCriterion("front_ui >", value, "frontUi");
            return (Criteria) this;
        }

        public Criteria andFrontUiGreaterThanOrEqualTo(String value) {
            addCriterion("front_ui >=", value, "frontUi");
            return (Criteria) this;
        }

        public Criteria andFrontUiLessThan(String value) {
            addCriterion("front_ui <", value, "frontUi");
            return (Criteria) this;
        }

        public Criteria andFrontUiLessThanOrEqualTo(String value) {
            addCriterion("front_ui <=", value, "frontUi");
            return (Criteria) this;
        }

        public Criteria andFrontUiLike(String value) {
            addCriterion("front_ui like", value, "frontUi");
            return (Criteria) this;
        }

        public Criteria andFrontUiNotLike(String value) {
            addCriterion("front_ui not like", value, "frontUi");
            return (Criteria) this;
        }

        public Criteria andFrontUiIn(List<String> values) {
            addCriterion("front_ui in", values, "frontUi");
            return (Criteria) this;
        }

        public Criteria andFrontUiNotIn(List<String> values) {
            addCriterion("front_ui not in", values, "frontUi");
            return (Criteria) this;
        }

        public Criteria andFrontUiBetween(String value1, String value2) {
            addCriterion("front_ui between", value1, value2, "frontUi");
            return (Criteria) this;
        }

        public Criteria andFrontUiNotBetween(String value1, String value2) {
            addCriterion("front_ui not between", value1, value2, "frontUi");
            return (Criteria) this;
        }

        public Criteria andBackUeIsNull() {
            addCriterion("back_ue is null");
            return (Criteria) this;
        }

        public Criteria andBackUeIsNotNull() {
            addCriterion("back_ue is not null");
            return (Criteria) this;
        }

        public Criteria andBackUeEqualTo(String value) {
            addCriterion("back_ue =", value, "backUe");
            return (Criteria) this;
        }

        public Criteria andBackUeNotEqualTo(String value) {
            addCriterion("back_ue <>", value, "backUe");
            return (Criteria) this;
        }

        public Criteria andBackUeGreaterThan(String value) {
            addCriterion("back_ue >", value, "backUe");
            return (Criteria) this;
        }

        public Criteria andBackUeGreaterThanOrEqualTo(String value) {
            addCriterion("back_ue >=", value, "backUe");
            return (Criteria) this;
        }

        public Criteria andBackUeLessThan(String value) {
            addCriterion("back_ue <", value, "backUe");
            return (Criteria) this;
        }

        public Criteria andBackUeLessThanOrEqualTo(String value) {
            addCriterion("back_ue <=", value, "backUe");
            return (Criteria) this;
        }

        public Criteria andBackUeLike(String value) {
            addCriterion("back_ue like", value, "backUe");
            return (Criteria) this;
        }

        public Criteria andBackUeNotLike(String value) {
            addCriterion("back_ue not like", value, "backUe");
            return (Criteria) this;
        }

        public Criteria andBackUeIn(List<String> values) {
            addCriterion("back_ue in", values, "backUe");
            return (Criteria) this;
        }

        public Criteria andBackUeNotIn(List<String> values) {
            addCriterion("back_ue not in", values, "backUe");
            return (Criteria) this;
        }

        public Criteria andBackUeBetween(String value1, String value2) {
            addCriterion("back_ue between", value1, value2, "backUe");
            return (Criteria) this;
        }

        public Criteria andBackUeNotBetween(String value1, String value2) {
            addCriterion("back_ue not between", value1, value2, "backUe");
            return (Criteria) this;
        }

        public Criteria andBackUiIsNull() {
            addCriterion("back_ui is null");
            return (Criteria) this;
        }

        public Criteria andBackUiIsNotNull() {
            addCriterion("back_ui is not null");
            return (Criteria) this;
        }

        public Criteria andBackUiEqualTo(String value) {
            addCriterion("back_ui =", value, "backUi");
            return (Criteria) this;
        }

        public Criteria andBackUiNotEqualTo(String value) {
            addCriterion("back_ui <>", value, "backUi");
            return (Criteria) this;
        }

        public Criteria andBackUiGreaterThan(String value) {
            addCriterion("back_ui >", value, "backUi");
            return (Criteria) this;
        }

        public Criteria andBackUiGreaterThanOrEqualTo(String value) {
            addCriterion("back_ui >=", value, "backUi");
            return (Criteria) this;
        }

        public Criteria andBackUiLessThan(String value) {
            addCriterion("back_ui <", value, "backUi");
            return (Criteria) this;
        }

        public Criteria andBackUiLessThanOrEqualTo(String value) {
            addCriterion("back_ui <=", value, "backUi");
            return (Criteria) this;
        }

        public Criteria andBackUiLike(String value) {
            addCriterion("back_ui like", value, "backUi");
            return (Criteria) this;
        }

        public Criteria andBackUiNotLike(String value) {
            addCriterion("back_ui not like", value, "backUi");
            return (Criteria) this;
        }

        public Criteria andBackUiIn(List<String> values) {
            addCriterion("back_ui in", values, "backUi");
            return (Criteria) this;
        }

        public Criteria andBackUiNotIn(List<String> values) {
            addCriterion("back_ui not in", values, "backUi");
            return (Criteria) this;
        }

        public Criteria andBackUiBetween(String value1, String value2) {
            addCriterion("back_ui between", value1, value2, "backUi");
            return (Criteria) this;
        }

        public Criteria andBackUiNotBetween(String value1, String value2) {
            addCriterion("back_ui not between", value1, value2, "backUi");
            return (Criteria) this;
        }

        public Criteria andSvnIsNull() {
            addCriterion("svn is null");
            return (Criteria) this;
        }

        public Criteria andSvnIsNotNull() {
            addCriterion("svn is not null");
            return (Criteria) this;
        }

        public Criteria andSvnEqualTo(String value) {
            addCriterion("svn =", value, "svn");
            return (Criteria) this;
        }

        public Criteria andSvnNotEqualTo(String value) {
            addCriterion("svn <>", value, "svn");
            return (Criteria) this;
        }

        public Criteria andSvnGreaterThan(String value) {
            addCriterion("svn >", value, "svn");
            return (Criteria) this;
        }

        public Criteria andSvnGreaterThanOrEqualTo(String value) {
            addCriterion("svn >=", value, "svn");
            return (Criteria) this;
        }

        public Criteria andSvnLessThan(String value) {
            addCriterion("svn <", value, "svn");
            return (Criteria) this;
        }

        public Criteria andSvnLessThanOrEqualTo(String value) {
            addCriterion("svn <=", value, "svn");
            return (Criteria) this;
        }

        public Criteria andSvnLike(String value) {
            addCriterion("svn like", value, "svn");
            return (Criteria) this;
        }

        public Criteria andSvnNotLike(String value) {
            addCriterion("svn not like", value, "svn");
            return (Criteria) this;
        }

        public Criteria andSvnIn(List<String> values) {
            addCriterion("svn in", values, "svn");
            return (Criteria) this;
        }

        public Criteria andSvnNotIn(List<String> values) {
            addCriterion("svn not in", values, "svn");
            return (Criteria) this;
        }

        public Criteria andSvnBetween(String value1, String value2) {
            addCriterion("svn between", value1, value2, "svn");
            return (Criteria) this;
        }

        public Criteria andSvnNotBetween(String value1, String value2) {
            addCriterion("svn not between", value1, value2, "svn");
            return (Criteria) this;
        }

        public Criteria andRequirementDocIsNull() {
            addCriterion("requirement_doc is null");
            return (Criteria) this;
        }

        public Criteria andRequirementDocIsNotNull() {
            addCriterion("requirement_doc is not null");
            return (Criteria) this;
        }

        public Criteria andRequirementDocEqualTo(String value) {
            addCriterion("requirement_doc =", value, "requirementDoc");
            return (Criteria) this;
        }

        public Criteria andRequirementDocNotEqualTo(String value) {
            addCriterion("requirement_doc <>", value, "requirementDoc");
            return (Criteria) this;
        }

        public Criteria andRequirementDocGreaterThan(String value) {
            addCriterion("requirement_doc >", value, "requirementDoc");
            return (Criteria) this;
        }

        public Criteria andRequirementDocGreaterThanOrEqualTo(String value) {
            addCriterion("requirement_doc >=", value, "requirementDoc");
            return (Criteria) this;
        }

        public Criteria andRequirementDocLessThan(String value) {
            addCriterion("requirement_doc <", value, "requirementDoc");
            return (Criteria) this;
        }

        public Criteria andRequirementDocLessThanOrEqualTo(String value) {
            addCriterion("requirement_doc <=", value, "requirementDoc");
            return (Criteria) this;
        }

        public Criteria andRequirementDocLike(String value) {
            addCriterion("requirement_doc like", value, "requirementDoc");
            return (Criteria) this;
        }

        public Criteria andRequirementDocNotLike(String value) {
            addCriterion("requirement_doc not like", value, "requirementDoc");
            return (Criteria) this;
        }

        public Criteria andRequirementDocIn(List<String> values) {
            addCriterion("requirement_doc in", values, "requirementDoc");
            return (Criteria) this;
        }

        public Criteria andRequirementDocNotIn(List<String> values) {
            addCriterion("requirement_doc not in", values, "requirementDoc");
            return (Criteria) this;
        }

        public Criteria andRequirementDocBetween(String value1, String value2) {
            addCriterion("requirement_doc between", value1, value2, "requirementDoc");
            return (Criteria) this;
        }

        public Criteria andRequirementDocNotBetween(String value1, String value2) {
            addCriterion("requirement_doc not between", value1, value2, "requirementDoc");
            return (Criteria) this;
        }

        public Criteria andAcceptanceDocIsNull() {
            addCriterion("acceptance_doc is null");
            return (Criteria) this;
        }

        public Criteria andAcceptanceDocIsNotNull() {
            addCriterion("acceptance_doc is not null");
            return (Criteria) this;
        }

        public Criteria andAcceptanceDocEqualTo(String value) {
            addCriterion("acceptance_doc =", value, "acceptanceDoc");
            return (Criteria) this;
        }

        public Criteria andAcceptanceDocNotEqualTo(String value) {
            addCriterion("acceptance_doc <>", value, "acceptanceDoc");
            return (Criteria) this;
        }

        public Criteria andAcceptanceDocGreaterThan(String value) {
            addCriterion("acceptance_doc >", value, "acceptanceDoc");
            return (Criteria) this;
        }

        public Criteria andAcceptanceDocGreaterThanOrEqualTo(String value) {
            addCriterion("acceptance_doc >=", value, "acceptanceDoc");
            return (Criteria) this;
        }

        public Criteria andAcceptanceDocLessThan(String value) {
            addCriterion("acceptance_doc <", value, "acceptanceDoc");
            return (Criteria) this;
        }

        public Criteria andAcceptanceDocLessThanOrEqualTo(String value) {
            addCriterion("acceptance_doc <=", value, "acceptanceDoc");
            return (Criteria) this;
        }

        public Criteria andAcceptanceDocLike(String value) {
            addCriterion("acceptance_doc like", value, "acceptanceDoc");
            return (Criteria) this;
        }

        public Criteria andAcceptanceDocNotLike(String value) {
            addCriterion("acceptance_doc not like", value, "acceptanceDoc");
            return (Criteria) this;
        }

        public Criteria andAcceptanceDocIn(List<String> values) {
            addCriterion("acceptance_doc in", values, "acceptanceDoc");
            return (Criteria) this;
        }

        public Criteria andAcceptanceDocNotIn(List<String> values) {
            addCriterion("acceptance_doc not in", values, "acceptanceDoc");
            return (Criteria) this;
        }

        public Criteria andAcceptanceDocBetween(String value1, String value2) {
            addCriterion("acceptance_doc between", value1, value2, "acceptanceDoc");
            return (Criteria) this;
        }

        public Criteria andAcceptanceDocNotBetween(String value1, String value2) {
            addCriterion("acceptance_doc not between", value1, value2, "acceptanceDoc");
            return (Criteria) this;
        }

        public Criteria andIsDelIsNull() {
            addCriterion("is_del is null");
            return (Criteria) this;
        }

        public Criteria andIsDelIsNotNull() {
            addCriterion("is_del is not null");
            return (Criteria) this;
        }

        public Criteria andIsDelEqualTo(Integer value) {
            addCriterion("is_del =", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotEqualTo(Integer value) {
            addCriterion("is_del <>", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelGreaterThan(Integer value) {
            addCriterion("is_del >", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_del >=", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelLessThan(Integer value) {
            addCriterion("is_del <", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelLessThanOrEqualTo(Integer value) {
            addCriterion("is_del <=", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelIn(List<Integer> values) {
            addCriterion("is_del in", values, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotIn(List<Integer> values) {
            addCriterion("is_del not in", values, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelBetween(Integer value1, Integer value2) {
            addCriterion("is_del between", value1, value2, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotBetween(Integer value1, Integer value2) {
            addCriterion("is_del not between", value1, value2, "isDel");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table version_alpha
     *
     * @mbg.generated do_not_delete_during_merge Thu Sep 24 15:15:01 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table version_alpha
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}