package com.echair.project_manage.dao.model;

import java.util.Date;

public class Alpha {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_alpha.id
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_alpha.vaersion
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    private String vaersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_alpha.vaersion_id
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    private Integer vaersionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_alpha.project_id
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    private Long projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_alpha.front_ue
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    private String frontUe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_alpha.front_ui
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    private String frontUi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_alpha.back_ue
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    private String backUe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_alpha.back_ui
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    private String backUi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_alpha.svn
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    private String svn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_alpha.requirement_doc
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    private String requirementDoc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_alpha.acceptance_doc
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    private String acceptanceDoc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_alpha.is_del
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    private Integer isDel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_alpha.create_time
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_alpha.update_time
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_alpha.id
     *
     * @return the value of version_alpha.id
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_alpha.id
     *
     * @param id the value for version_alpha.id
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_alpha.vaersion
     *
     * @return the value of version_alpha.vaersion
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public String getVaersion() {
        return vaersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_alpha.vaersion
     *
     * @param vaersion the value for version_alpha.vaersion
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public void setVaersion(String vaersion) {
        this.vaersion = vaersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_alpha.vaersion_id
     *
     * @return the value of version_alpha.vaersion_id
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public Integer getVaersionId() {
        return vaersionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_alpha.vaersion_id
     *
     * @param vaersionId the value for version_alpha.vaersion_id
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public void setVaersionId(Integer vaersionId) {
        this.vaersionId = vaersionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_alpha.project_id
     *
     * @return the value of version_alpha.project_id
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public Long getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_alpha.project_id
     *
     * @param projectId the value for version_alpha.project_id
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_alpha.front_ue
     *
     * @return the value of version_alpha.front_ue
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public String getFrontUe() {
        return frontUe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_alpha.front_ue
     *
     * @param frontUe the value for version_alpha.front_ue
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public void setFrontUe(String frontUe) {
        this.frontUe = frontUe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_alpha.front_ui
     *
     * @return the value of version_alpha.front_ui
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public String getFrontUi() {
        return frontUi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_alpha.front_ui
     *
     * @param frontUi the value for version_alpha.front_ui
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public void setFrontUi(String frontUi) {
        this.frontUi = frontUi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_alpha.back_ue
     *
     * @return the value of version_alpha.back_ue
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public String getBackUe() {
        return backUe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_alpha.back_ue
     *
     * @param backUe the value for version_alpha.back_ue
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public void setBackUe(String backUe) {
        this.backUe = backUe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_alpha.back_ui
     *
     * @return the value of version_alpha.back_ui
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public String getBackUi() {
        return backUi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_alpha.back_ui
     *
     * @param backUi the value for version_alpha.back_ui
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public void setBackUi(String backUi) {
        this.backUi = backUi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_alpha.svn
     *
     * @return the value of version_alpha.svn
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public String getSvn() {
        return svn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_alpha.svn
     *
     * @param svn the value for version_alpha.svn
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public void setSvn(String svn) {
        this.svn = svn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_alpha.requirement_doc
     *
     * @return the value of version_alpha.requirement_doc
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public String getRequirementDoc() {
        return requirementDoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_alpha.requirement_doc
     *
     * @param requirementDoc the value for version_alpha.requirement_doc
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public void setRequirementDoc(String requirementDoc) {
        this.requirementDoc = requirementDoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_alpha.acceptance_doc
     *
     * @return the value of version_alpha.acceptance_doc
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public String getAcceptanceDoc() {
        return acceptanceDoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_alpha.acceptance_doc
     *
     * @param acceptanceDoc the value for version_alpha.acceptance_doc
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public void setAcceptanceDoc(String acceptanceDoc) {
        this.acceptanceDoc = acceptanceDoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_alpha.is_del
     *
     * @return the value of version_alpha.is_del
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_alpha.is_del
     *
     * @param isDel the value for version_alpha.is_del
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_alpha.create_time
     *
     * @return the value of version_alpha.create_time
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_alpha.create_time
     *
     * @param createTime the value for version_alpha.create_time
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_alpha.update_time
     *
     * @return the value of version_alpha.update_time
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_alpha.update_time
     *
     * @param updateTime the value for version_alpha.update_time
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}