package com.echair.project_manage.dao.model;

import java.util.Date;

public class Assess {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assess.assess_id
     *
     * @mbg.generated Sat Aug 29 17:19:54 CST 2020
     */
    private Long assessId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assess.assess_name
     *
     * @mbg.generated Sat Aug 29 17:19:54 CST 2020
     */
    private String assessName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assess.type
     *
     * @mbg.generated Sat Aug 29 17:19:54 CST 2020
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assess.pid
     *
     * @mbg.generated Sat Aug 29 17:19:54 CST 2020
     */
    private Long pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assess.url
     *
     * @mbg.generated Sat Aug 29 17:19:54 CST 2020
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assess.is_del
     *
     * @mbg.generated Sat Aug 29 17:19:54 CST 2020
     */
    private Integer isDel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assess.create_time
     *
     * @mbg.generated Sat Aug 29 17:19:54 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assess.update_time
     *
     * @mbg.generated Sat Aug 29 17:19:54 CST 2020
     */
    private Date updateTime;

    private long roleId;

    public long getRoleId() {
        return roleId;
    }

    public void setRoleId(long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assess.assess_id
     *
     * @return the value of assess.assess_id
     *
     * @mbg.generated Sat Aug 29 17:19:54 CST 2020
     */
    public Long getAssessId() {
        return assessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assess.assess_id
     *
     * @param assessId the value for assess.assess_id
     *
     * @mbg.generated Sat Aug 29 17:19:54 CST 2020
     */
    public void setAssessId(Long assessId) {
        this.assessId = assessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assess.assess_name
     *
     * @return the value of assess.assess_name
     *
     * @mbg.generated Sat Aug 29 17:19:54 CST 2020
     */
    public String getAssessName() {
        return assessName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assess.assess_name
     *
     * @param assessName the value for assess.assess_name
     *
     * @mbg.generated Sat Aug 29 17:19:54 CST 2020
     */
    public void setAssessName(String assessName) {
        this.assessName = assessName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assess.type
     *
     * @return the value of assess.type
     *
     * @mbg.generated Sat Aug 29 17:19:54 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assess.type
     *
     * @param type the value for assess.type
     *
     * @mbg.generated Sat Aug 29 17:19:54 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assess.pid
     *
     * @return the value of assess.pid
     *
     * @mbg.generated Sat Aug 29 17:19:54 CST 2020
     */
    public Long getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assess.pid
     *
     * @param pid the value for assess.pid
     *
     * @mbg.generated Sat Aug 29 17:19:54 CST 2020
     */
    public void setPid(Long pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assess.url
     *
     * @return the value of assess.url
     *
     * @mbg.generated Sat Aug 29 17:19:54 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assess.url
     *
     * @param url the value for assess.url
     *
     * @mbg.generated Sat Aug 29 17:19:54 CST 2020
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assess.is_del
     *
     * @return the value of assess.is_del
     *
     * @mbg.generated Sat Aug 29 17:19:54 CST 2020
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assess.is_del
     *
     * @param isDel the value for assess.is_del
     *
     * @mbg.generated Sat Aug 29 17:19:54 CST 2020
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assess.create_time
     *
     * @return the value of assess.create_time
     *
     * @mbg.generated Sat Aug 29 17:19:54 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assess.create_time
     *
     * @param createTime the value for assess.create_time
     *
     * @mbg.generated Sat Aug 29 17:19:54 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assess.update_time
     *
     * @return the value of assess.update_time
     *
     * @mbg.generated Sat Aug 29 17:19:54 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assess.update_time
     *
     * @param updateTime the value for assess.update_time
     *
     * @mbg.generated Sat Aug 29 17:19:54 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}