package com.echair.project_manage.dao.model;

import java.util.Date;

public class AssessRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assess_role.id
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assess_role.assess_id
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    private Long assessId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assess_role.role_id
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    private Long roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assess_role.is_del
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    private Integer isDel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assess_role.create_time
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assess_role.update_time
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assess_role.id
     *
     * @return the value of assess_role.id
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assess_role.id
     *
     * @param id the value for assess_role.id
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assess_role.assess_id
     *
     * @return the value of assess_role.assess_id
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    public Long getAssessId() {
        return assessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assess_role.assess_id
     *
     * @param assessId the value for assess_role.assess_id
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    public void setAssessId(Long assessId) {
        this.assessId = assessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assess_role.role_id
     *
     * @return the value of assess_role.role_id
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assess_role.role_id
     *
     * @param roleId the value for assess_role.role_id
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assess_role.is_del
     *
     * @return the value of assess_role.is_del
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assess_role.is_del
     *
     * @param isDel the value for assess_role.is_del
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assess_role.create_time
     *
     * @return the value of assess_role.create_time
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assess_role.create_time
     *
     * @param createTime the value for assess_role.create_time
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assess_role.update_time
     *
     * @return the value of assess_role.update_time
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assess_role.update_time
     *
     * @param updateTime the value for assess_role.update_time
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}