package com.echair.project_manage.dao.model;

import java.util.Date;

public class Beta {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_beta.id
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_beta.version
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    private String version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_beta.version_id
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    private Integer versionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_beta.project_id
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    private Long projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_beta.front_url
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    private String frontUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_beta.back_url
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    private String backUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_beta.api_doc
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    private String apiDoc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_beta.requirement_doc
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    private String requirementDoc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_beta.acceptance_doc
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    private String acceptanceDoc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_beta.is_del
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    private Integer isDel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_beta.create_time
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_beta.update_time
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_beta.test_doc
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    private String testDoc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_beta.id
     *
     * @return the value of version_beta.id
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_beta.id
     *
     * @param id the value for version_beta.id
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_beta.version
     *
     * @return the value of version_beta.version
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_beta.version
     *
     * @param version the value for version_beta.version
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_beta.version_id
     *
     * @return the value of version_beta.version_id
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public Integer getVersionId() {
        return versionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_beta.version_id
     *
     * @param versionId the value for version_beta.version_id
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public void setVersionId(Integer versionId) {
        this.versionId = versionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_beta.project_id
     *
     * @return the value of version_beta.project_id
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public Long getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_beta.project_id
     *
     * @param projectId the value for version_beta.project_id
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_beta.front_url
     *
     * @return the value of version_beta.front_url
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public String getFrontUrl() {
        return frontUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_beta.front_url
     *
     * @param frontUrl the value for version_beta.front_url
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public void setFrontUrl(String frontUrl) {
        this.frontUrl = frontUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_beta.back_url
     *
     * @return the value of version_beta.back_url
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public String getBackUrl() {
        return backUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_beta.back_url
     *
     * @param backUrl the value for version_beta.back_url
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public void setBackUrl(String backUrl) {
        this.backUrl = backUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_beta.api_doc
     *
     * @return the value of version_beta.api_doc
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public String getApiDoc() {
        return apiDoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_beta.api_doc
     *
     * @param apiDoc the value for version_beta.api_doc
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public void setApiDoc(String apiDoc) {
        this.apiDoc = apiDoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_beta.requirement_doc
     *
     * @return the value of version_beta.requirement_doc
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public String getRequirementDoc() {
        return requirementDoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_beta.requirement_doc
     *
     * @param requirementDoc the value for version_beta.requirement_doc
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public void setRequirementDoc(String requirementDoc) {
        this.requirementDoc = requirementDoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_beta.acceptance_doc
     *
     * @return the value of version_beta.acceptance_doc
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public String getAcceptanceDoc() {
        return acceptanceDoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_beta.acceptance_doc
     *
     * @param acceptanceDoc the value for version_beta.acceptance_doc
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public void setAcceptanceDoc(String acceptanceDoc) {
        this.acceptanceDoc = acceptanceDoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_beta.is_del
     *
     * @return the value of version_beta.is_del
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_beta.is_del
     *
     * @param isDel the value for version_beta.is_del
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_beta.create_time
     *
     * @return the value of version_beta.create_time
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_beta.create_time
     *
     * @param createTime the value for version_beta.create_time
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_beta.update_time
     *
     * @return the value of version_beta.update_time
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_beta.update_time
     *
     * @param updateTime the value for version_beta.update_time
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_beta.test_doc
     *
     * @return the value of version_beta.test_doc
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public String getTestDoc() {
        return testDoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_beta.test_doc
     *
     * @param testDoc the value for version_beta.test_doc
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public void setTestDoc(String testDoc) {
        this.testDoc = testDoc;
    }
}