package com.echair.project_manage.dao.model;

public class File {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.file_id
     *
     * @mbg.generated Mon Sep 14 14:11:40 CST 2020
     */
    private Long fileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.file_name
     *
     * @mbg.generated Mon Sep 14 14:11:40 CST 2020
     */
    private String fileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.project_id
     *
     * @mbg.generated Mon Sep 14 14:11:40 CST 2020
     */
    private Long projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.is_del
     *
     * @mbg.generated Mon Sep 14 14:11:40 CST 2020
     */
    private Integer isDel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.url
     *
     * @mbg.generated Mon Sep 14 14:11:40 CST 2020
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.file_id
     *
     * @return the value of file.file_id
     *
     * @mbg.generated Mon Sep 14 14:11:40 CST 2020
     */
    public Long getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.file_id
     *
     * @param fileId the value for file.file_id
     *
     * @mbg.generated Mon Sep 14 14:11:40 CST 2020
     */
    public void setFileId(Long fileId) {
        this.fileId = fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.file_name
     *
     * @return the value of file.file_name
     *
     * @mbg.generated Mon Sep 14 14:11:40 CST 2020
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.file_name
     *
     * @param fileName the value for file.file_name
     *
     * @mbg.generated Mon Sep 14 14:11:40 CST 2020
     */
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.project_id
     *
     * @return the value of file.project_id
     *
     * @mbg.generated Mon Sep 14 14:11:40 CST 2020
     */
    public Long getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.project_id
     *
     * @param projectId the value for file.project_id
     *
     * @mbg.generated Mon Sep 14 14:11:40 CST 2020
     */
    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.is_del
     *
     * @return the value of file.is_del
     *
     * @mbg.generated Mon Sep 14 14:11:40 CST 2020
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.is_del
     *
     * @param isDel the value for file.is_del
     *
     * @mbg.generated Mon Sep 14 14:11:40 CST 2020
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.url
     *
     * @return the value of file.url
     *
     * @mbg.generated Mon Sep 14 14:11:40 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.url
     *
     * @param url the value for file.url
     *
     * @mbg.generated Mon Sep 14 14:11:40 CST 2020
     */
    public void setUrl(String url) {
        this.url = url;
    }
}