package com.echair.project_manage.dao.model;

import java.util.Date;

public class Master {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_master.id
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_master.version
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    private String version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_master.version_id
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    private Integer versionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_master.project_id
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    private Long projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_master.operation_doc
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    private String operationDoc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_master.database_doc
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    private String databaseDoc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_master.api_doc
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    private String apiDoc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_master.acceptance_doc
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    private String acceptanceDoc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_master.is_del
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    private Integer isDel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_master.create_time
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_master.update_time
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_master.id
     *
     * @return the value of version_master.id
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_master.id
     *
     * @param id the value for version_master.id
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_master.version
     *
     * @return the value of version_master.version
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_master.version
     *
     * @param version the value for version_master.version
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_master.version_id
     *
     * @return the value of version_master.version_id
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public Integer getVersionId() {
        return versionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_master.version_id
     *
     * @param versionId the value for version_master.version_id
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public void setVersionId(Integer versionId) {
        this.versionId = versionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_master.project_id
     *
     * @return the value of version_master.project_id
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public Long getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_master.project_id
     *
     * @param projectId the value for version_master.project_id
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_master.operation_doc
     *
     * @return the value of version_master.operation_doc
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public String getOperationDoc() {
        return operationDoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_master.operation_doc
     *
     * @param operationDoc the value for version_master.operation_doc
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public void setOperationDoc(String operationDoc) {
        this.operationDoc = operationDoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_master.database_doc
     *
     * @return the value of version_master.database_doc
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public String getDatabaseDoc() {
        return databaseDoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_master.database_doc
     *
     * @param databaseDoc the value for version_master.database_doc
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public void setDatabaseDoc(String databaseDoc) {
        this.databaseDoc = databaseDoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_master.api_doc
     *
     * @return the value of version_master.api_doc
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public String getApiDoc() {
        return apiDoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_master.api_doc
     *
     * @param apiDoc the value for version_master.api_doc
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public void setApiDoc(String apiDoc) {
        this.apiDoc = apiDoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_master.acceptance_doc
     *
     * @return the value of version_master.acceptance_doc
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public String getAcceptanceDoc() {
        return acceptanceDoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_master.acceptance_doc
     *
     * @param acceptanceDoc the value for version_master.acceptance_doc
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public void setAcceptanceDoc(String acceptanceDoc) {
        this.acceptanceDoc = acceptanceDoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_master.is_del
     *
     * @return the value of version_master.is_del
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_master.is_del
     *
     * @param isDel the value for version_master.is_del
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_master.create_time
     *
     * @return the value of version_master.create_time
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_master.create_time
     *
     * @param createTime the value for version_master.create_time
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_master.update_time
     *
     * @return the value of version_master.update_time
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_master.update_time
     *
     * @param updateTime the value for version_master.update_time
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}