package com.echair.project_manage.dao.model;

import java.util.Date;

public class Message {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.message_id
     *
     * @mbg.generated Thu Sep 17 14:22:38 CST 2020
     */
    private Long messageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.name
     *
     * @mbg.generated Thu Sep 17 14:22:38 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.userid
     *
     * @mbg.generated Thu Sep 17 14:22:38 CST 2020
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.url
     *
     * @mbg.generated Thu Sep 17 14:22:38 CST 2020
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.content
     *
     * @mbg.generated Thu Sep 17 14:22:38 CST 2020
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.is_del
     *
     * @mbg.generated Thu Sep 17 14:22:38 CST 2020
     */
    private Integer isDel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.project_id
     *
     * @mbg.generated Thu Sep 17 14:22:38 CST 2020
     */
    private Long projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.create_time
     *
     * @mbg.generated Thu Sep 17 14:22:38 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.uodate_time
     *
     * @mbg.generated Thu Sep 17 14:22:38 CST 2020
     */
    private Date uodateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.avater
     *
     * @mbg.generated Thu Sep 17 14:22:38 CST 2020
     */
    private String avater;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.message_id
     *
     * @return the value of message.message_id
     *
     * @mbg.generated Thu Sep 17 14:22:38 CST 2020
     */
    public Long getMessageId() {
        return messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.message_id
     *
     * @param messageId the value for message.message_id
     *
     * @mbg.generated Thu Sep 17 14:22:38 CST 2020
     */
    public void setMessageId(Long messageId) {
        this.messageId = messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.name
     *
     * @return the value of message.name
     *
     * @mbg.generated Thu Sep 17 14:22:38 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.name
     *
     * @param name the value for message.name
     *
     * @mbg.generated Thu Sep 17 14:22:38 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.userid
     *
     * @return the value of message.userid
     *
     * @mbg.generated Thu Sep 17 14:22:38 CST 2020
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.userid
     *
     * @param userid the value for message.userid
     *
     * @mbg.generated Thu Sep 17 14:22:38 CST 2020
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.url
     *
     * @return the value of message.url
     *
     * @mbg.generated Thu Sep 17 14:22:38 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.url
     *
     * @param url the value for message.url
     *
     * @mbg.generated Thu Sep 17 14:22:38 CST 2020
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.content
     *
     * @return the value of message.content
     *
     * @mbg.generated Thu Sep 17 14:22:38 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.content
     *
     * @param content the value for message.content
     *
     * @mbg.generated Thu Sep 17 14:22:38 CST 2020
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.is_del
     *
     * @return the value of message.is_del
     *
     * @mbg.generated Thu Sep 17 14:22:38 CST 2020
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.is_del
     *
     * @param isDel the value for message.is_del
     *
     * @mbg.generated Thu Sep 17 14:22:38 CST 2020
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.project_id
     *
     * @return the value of message.project_id
     *
     * @mbg.generated Thu Sep 17 14:22:38 CST 2020
     */
    public Long getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.project_id
     *
     * @param projectId the value for message.project_id
     *
     * @mbg.generated Thu Sep 17 14:22:38 CST 2020
     */
    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.create_time
     *
     * @return the value of message.create_time
     *
     * @mbg.generated Thu Sep 17 14:22:38 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.create_time
     *
     * @param createTime the value for message.create_time
     *
     * @mbg.generated Thu Sep 17 14:22:38 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.uodate_time
     *
     * @return the value of message.uodate_time
     *
     * @mbg.generated Thu Sep 17 14:22:38 CST 2020
     */
    public Date getUodateTime() {
        return uodateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.uodate_time
     *
     * @param uodateTime the value for message.uodate_time
     *
     * @mbg.generated Thu Sep 17 14:22:38 CST 2020
     */
    public void setUodateTime(Date uodateTime) {
        this.uodateTime = uodateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.avater
     *
     * @return the value of message.avater
     *
     * @mbg.generated Thu Sep 17 14:22:38 CST 2020
     */
    public String getAvater() {
        return avater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.avater
     *
     * @param avater the value for message.avater
     *
     * @mbg.generated Thu Sep 17 14:22:38 CST 2020
     */
    public void setAvater(String avater) {
        this.avater = avater;
    }
}