package com.echair.project_manage.dao.model;

import java.util.Date;

public class Participation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column participation.id
     *
     * @mbg.generated Mon Sep 14 15:37:24 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column participation.name
     *
     * @mbg.generated Mon Sep 14 15:37:24 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column participation.userid
     *
     * @mbg.generated Mon Sep 14 15:37:24 CST 2020
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column participation.project_id
     *
     * @mbg.generated Mon Sep 14 15:37:24 CST 2020
     */
    private Long projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column participation.station
     *
     * @mbg.generated Mon Sep 14 15:37:24 CST 2020
     */
    private String station;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column participation.is_executed
     *
     * @mbg.generated Mon Sep 14 15:37:24 CST 2020
     */
    private Integer isExecuted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column participation.is_del
     *
     * @mbg.generated Mon Sep 14 15:37:24 CST 2020
     */
    private Integer isDel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column participation.create_time
     *
     * @mbg.generated Mon Sep 14 15:37:24 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column participation.update_time
     *
     * @mbg.generated Mon Sep 14 15:37:24 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column participation.id
     *
     * @return the value of participation.id
     *
     * @mbg.generated Mon Sep 14 15:37:24 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column participation.id
     *
     * @param id the value for participation.id
     *
     * @mbg.generated Mon Sep 14 15:37:24 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column participation.name
     *
     * @return the value of participation.name
     *
     * @mbg.generated Mon Sep 14 15:37:24 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column participation.name
     *
     * @param name the value for participation.name
     *
     * @mbg.generated Mon Sep 14 15:37:24 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column participation.userid
     *
     * @return the value of participation.userid
     *
     * @mbg.generated Mon Sep 14 15:37:24 CST 2020
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column participation.userid
     *
     * @param userid the value for participation.userid
     *
     * @mbg.generated Mon Sep 14 15:37:24 CST 2020
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column participation.project_id
     *
     * @return the value of participation.project_id
     *
     * @mbg.generated Mon Sep 14 15:37:24 CST 2020
     */
    public Long getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column participation.project_id
     *
     * @param projectId the value for participation.project_id
     *
     * @mbg.generated Mon Sep 14 15:37:24 CST 2020
     */
    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column participation.station
     *
     * @return the value of participation.station
     *
     * @mbg.generated Mon Sep 14 15:37:24 CST 2020
     */
    public String getStation() {
        return station;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column participation.station
     *
     * @param station the value for participation.station
     *
     * @mbg.generated Mon Sep 14 15:37:24 CST 2020
     */
    public void setStation(String station) {
        this.station = station;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column participation.is_executed
     *
     * @return the value of participation.is_executed
     *
     * @mbg.generated Mon Sep 14 15:37:24 CST 2020
     */
    public Integer getIsExecuted() {
        return isExecuted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column participation.is_executed
     *
     * @param isExecuted the value for participation.is_executed
     *
     * @mbg.generated Mon Sep 14 15:37:24 CST 2020
     */
    public void setIsExecuted(Integer isExecuted) {
        this.isExecuted = isExecuted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column participation.is_del
     *
     * @return the value of participation.is_del
     *
     * @mbg.generated Mon Sep 14 15:37:24 CST 2020
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column participation.is_del
     *
     * @param isDel the value for participation.is_del
     *
     * @mbg.generated Mon Sep 14 15:37:24 CST 2020
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column participation.create_time
     *
     * @return the value of participation.create_time
     *
     * @mbg.generated Mon Sep 14 15:37:24 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column participation.create_time
     *
     * @param createTime the value for participation.create_time
     *
     * @mbg.generated Mon Sep 14 15:37:24 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column participation.update_time
     *
     * @return the value of participation.update_time
     *
     * @mbg.generated Mon Sep 14 15:37:24 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column participation.update_time
     *
     * @param updateTime the value for participation.update_time
     *
     * @mbg.generated Mon Sep 14 15:37:24 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}