package com.echair.project_manage.dao.model;

import java.util.Date;

public class Project {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.project_id
     *
     * @mbg.generated Tue Sep 08 15:56:59 CST 2020
     */
    private Long projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.project_name
     *
     * @mbg.generated Tue Sep 08 15:56:59 CST 2020
     */
    private String projectName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.begin
     *
     * @mbg.generated Tue Sep 08 15:56:59 CST 2020
     */
    private Date begin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.end
     *
     * @mbg.generated Tue Sep 08 15:56:59 CST 2020
     */
    private Date end;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.version_id
     *
     * @mbg.generated Tue Sep 08 15:56:59 CST 2020
     */
    private Integer versionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.version_name
     *
     * @mbg.generated Tue Sep 08 15:56:59 CST 2020
     */
    private String versionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.contract_name
     *
     * @mbg.generated Tue Sep 08 15:56:59 CST 2020
     */
    private String contractName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.contract_tel
     *
     * @mbg.generated Tue Sep 08 15:56:59 CST 2020
     */
    private String contractTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.station
     *
     * @mbg.generated Tue Sep 08 15:56:59 CST 2020
     */
    private String station;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.rank
     *
     * @mbg.generated Tue Sep 08 15:56:59 CST 2020
     */
    private Integer rank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.manage_username
     *
     * @mbg.generated Tue Sep 08 15:56:59 CST 2020
     */
    private String manageUsername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.manage_userid
     *
     * @mbg.generated Tue Sep 08 15:56:59 CST 2020
     */
    private String manageUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.is_del
     *
     * @mbg.generated Tue Sep 08 15:56:59 CST 2020
     */
    private Integer isDel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.create_time
     *
     * @mbg.generated Tue Sep 08 15:56:59 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.update_time
     *
     * @mbg.generated Tue Sep 08 15:56:59 CST 2020
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.data
     *
     * @mbg.generated Tue Sep 08 15:56:59 CST 2020
     */
    private String data;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.project_id
     *
     * @return the value of project.project_id
     *
     * @mbg.generated Tue Sep 08 15:56:59 CST 2020
     */
    public Long getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.project_id
     *
     * @param projectId the value for project.project_id
     *
     * @mbg.generated Tue Sep 08 15:56:59 CST 2020
     */
    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.project_name
     *
     * @return the value of project.project_name
     *
     * @mbg.generated Tue Sep 08 15:56:59 CST 2020
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.project_name
     *
     * @param projectName the value for project.project_name
     *
     * @mbg.generated Tue Sep 08 15:56:59 CST 2020
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.begin
     *
     * @return the value of project.begin
     *
     * @mbg.generated Tue Sep 08 15:56:59 CST 2020
     */
    public Date getBegin() {
        return begin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.begin
     *
     * @param begin the value for project.begin
     *
     * @mbg.generated Tue Sep 08 15:56:59 CST 2020
     */
    public void setBegin(Date begin) {
        this.begin = begin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.end
     *
     * @return the value of project.end
     *
     * @mbg.generated Tue Sep 08 15:56:59 CST 2020
     */
    public Date getEnd() {
        return end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.end
     *
     * @param end the value for project.end
     *
     * @mbg.generated Tue Sep 08 15:56:59 CST 2020
     */
    public void setEnd(Date end) {
        this.end = end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.version_id
     *
     * @return the value of project.version_id
     *
     * @mbg.generated Tue Sep 08 15:56:59 CST 2020
     */
    public Integer getVersionId() {
        return versionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.version_id
     *
     * @param versionId the value for project.version_id
     *
     * @mbg.generated Tue Sep 08 15:56:59 CST 2020
     */
    public void setVersionId(Integer versionId) {
        this.versionId = versionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.version_name
     *
     * @return the value of project.version_name
     *
     * @mbg.generated Tue Sep 08 15:56:59 CST 2020
     */
    public String getVersionName() {
        return versionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.version_name
     *
     * @param versionName the value for project.version_name
     *
     * @mbg.generated Tue Sep 08 15:56:59 CST 2020
     */
    public void setVersionName(String versionName) {
        this.versionName = versionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.contract_name
     *
     * @return the value of project.contract_name
     *
     * @mbg.generated Tue Sep 08 15:56:59 CST 2020
     */
    public String getContractName() {
        return contractName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.contract_name
     *
     * @param contractName the value for project.contract_name
     *
     * @mbg.generated Tue Sep 08 15:56:59 CST 2020
     */
    public void setContractName(String contractName) {
        this.contractName = contractName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.contract_tel
     *
     * @return the value of project.contract_tel
     *
     * @mbg.generated Tue Sep 08 15:56:59 CST 2020
     */
    public String getContractTel() {
        return contractTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.contract_tel
     *
     * @param contractTel the value for project.contract_tel
     *
     * @mbg.generated Tue Sep 08 15:56:59 CST 2020
     */
    public void setContractTel(String contractTel) {
        this.contractTel = contractTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.station
     *
     * @return the value of project.station
     *
     * @mbg.generated Tue Sep 08 15:56:59 CST 2020
     */
    public String getStation() {
        return station;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.station
     *
     * @param station the value for project.station
     *
     * @mbg.generated Tue Sep 08 15:56:59 CST 2020
     */
    public void setStation(String station) {
        this.station = station;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.rank
     *
     * @return the value of project.rank
     *
     * @mbg.generated Tue Sep 08 15:56:59 CST 2020
     */
    public Integer getRank() {
        return rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.rank
     *
     * @param rank the value for project.rank
     *
     * @mbg.generated Tue Sep 08 15:56:59 CST 2020
     */
    public void setRank(Integer rank) {
        this.rank = rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.manage_username
     *
     * @return the value of project.manage_username
     *
     * @mbg.generated Tue Sep 08 15:56:59 CST 2020
     */
    public String getManageUsername() {
        return manageUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.manage_username
     *
     * @param manageUsername the value for project.manage_username
     *
     * @mbg.generated Tue Sep 08 15:56:59 CST 2020
     */
    public void setManageUsername(String manageUsername) {
        this.manageUsername = manageUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.manage_userid
     *
     * @return the value of project.manage_userid
     *
     * @mbg.generated Tue Sep 08 15:56:59 CST 2020
     */
    public String getManageUserid() {
        return manageUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.manage_userid
     *
     * @param manageUserid the value for project.manage_userid
     *
     * @mbg.generated Tue Sep 08 15:56:59 CST 2020
     */
    public void setManageUserid(String manageUserid) {
        this.manageUserid = manageUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.is_del
     *
     * @return the value of project.is_del
     *
     * @mbg.generated Tue Sep 08 15:56:59 CST 2020
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.is_del
     *
     * @param isDel the value for project.is_del
     *
     * @mbg.generated Tue Sep 08 15:56:59 CST 2020
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.create_time
     *
     * @return the value of project.create_time
     *
     * @mbg.generated Tue Sep 08 15:56:59 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.create_time
     *
     * @param createTime the value for project.create_time
     *
     * @mbg.generated Tue Sep 08 15:56:59 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.update_time
     *
     * @return the value of project.update_time
     *
     * @mbg.generated Tue Sep 08 15:56:59 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.update_time
     *
     * @param updateTime the value for project.update_time
     *
     * @mbg.generated Tue Sep 08 15:56:59 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.data
     *
     * @return the value of project.data
     *
     * @mbg.generated Tue Sep 08 15:56:59 CST 2020
     */
    public String getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.data
     *
     * @param data the value for project.data
     *
     * @mbg.generated Tue Sep 08 15:56:59 CST 2020
     */
    public void setData(String data) {
        this.data = data;
    }
}