package com.echair.project_manage.dao.model;

import java.util.Date;

public class Repository {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.id
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.repo_name
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    private String repoName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.key_word
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    private String keyWord;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.description
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.file_url
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    private String fileUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.code_url
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    private String codeUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.is_del
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    private Integer isDel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.create_time
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.update_time
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository.id
     *
     * @return the value of repository.id
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository.id
     *
     * @param id the value for repository.id
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository.repo_name
     *
     * @return the value of repository.repo_name
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    public String getRepoName() {
        return repoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository.repo_name
     *
     * @param repoName the value for repository.repo_name
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    public void setRepoName(String repoName) {
        this.repoName = repoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository.key_word
     *
     * @return the value of repository.key_word
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    public String getKeyWord() {
        return keyWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository.key_word
     *
     * @param keyWord the value for repository.key_word
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    public void setKeyWord(String keyWord) {
        this.keyWord = keyWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository.description
     *
     * @return the value of repository.description
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository.description
     *
     * @param description the value for repository.description
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository.file_url
     *
     * @return the value of repository.file_url
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    public String getFileUrl() {
        return fileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository.file_url
     *
     * @param fileUrl the value for repository.file_url
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    public void setFileUrl(String fileUrl) {
        this.fileUrl = fileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository.code_url
     *
     * @return the value of repository.code_url
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    public String getCodeUrl() {
        return codeUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository.code_url
     *
     * @param codeUrl the value for repository.code_url
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    public void setCodeUrl(String codeUrl) {
        this.codeUrl = codeUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository.is_del
     *
     * @return the value of repository.is_del
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository.is_del
     *
     * @param isDel the value for repository.is_del
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository.create_time
     *
     * @return the value of repository.create_time
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository.create_time
     *
     * @param createTime the value for repository.create_time
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository.update_time
     *
     * @return the value of repository.update_time
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository.update_time
     *
     * @param updateTime the value for repository.update_time
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}