package com.echair.project_manage.dao.model;

import java.util.Date;

public class Task {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.task_id
     *
     * @mbg.generated Mon Sep 07 16:51:36 CST 2020
     */
    private Long taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.task_name
     *
     * @mbg.generated Mon Sep 07 16:51:36 CST 2020
     */
    private String taskName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.execute_name
     *
     * @mbg.generated Mon Sep 07 16:51:36 CST 2020
     */
    private String executeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.execute_userid
     *
     * @mbg.generated Mon Sep 07 16:51:36 CST 2020
     */
    private String executeUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.project_id
     *
     * @mbg.generated Mon Sep 07 16:51:36 CST 2020
     */
    private Long projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.begin
     *
     * @mbg.generated Mon Sep 07 16:51:36 CST 2020
     */
    private Date begin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.end
     *
     * @mbg.generated Mon Sep 07 16:51:36 CST 2020
     */
    private Date end;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.is_completed
     *
     * @mbg.generated Mon Sep 07 16:51:36 CST 2020
     */
    private Integer isCompleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.status
     *
     * @mbg.generated Mon Sep 07 16:51:36 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.remark
     *
     * @mbg.generated Mon Sep 07 16:51:36 CST 2020
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.station
     *
     * @mbg.generated Mon Sep 07 16:51:36 CST 2020
     */
    private String station;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.is_del
     *
     * @mbg.generated Mon Sep 07 16:51:36 CST 2020
     */
    private Integer isDel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.create_time
     *
     * @mbg.generated Mon Sep 07 16:51:36 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.update_time
     *
     * @mbg.generated Mon Sep 07 16:51:36 CST 2020
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.over_days
     *
     * @mbg.generated Mon Sep 07 16:51:36 CST 2020
     */
    private Integer overDays;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.task_id
     *
     * @return the value of task.task_id
     *
     * @mbg.generated Mon Sep 07 16:51:36 CST 2020
     */
    public Long getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.task_id
     *
     * @param taskId the value for task.task_id
     *
     * @mbg.generated Mon Sep 07 16:51:36 CST 2020
     */
    public void setTaskId(Long taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.task_name
     *
     * @return the value of task.task_name
     *
     * @mbg.generated Mon Sep 07 16:51:36 CST 2020
     */
    public String getTaskName() {
        return taskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.task_name
     *
     * @param taskName the value for task.task_name
     *
     * @mbg.generated Mon Sep 07 16:51:36 CST 2020
     */
    public void setTaskName(String taskName) {
        this.taskName = taskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.execute_name
     *
     * @return the value of task.execute_name
     *
     * @mbg.generated Mon Sep 07 16:51:36 CST 2020
     */
    public String getExecuteName() {
        return executeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.execute_name
     *
     * @param executeName the value for task.execute_name
     *
     * @mbg.generated Mon Sep 07 16:51:36 CST 2020
     */
    public void setExecuteName(String executeName) {
        this.executeName = executeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.execute_userid
     *
     * @return the value of task.execute_userid
     *
     * @mbg.generated Mon Sep 07 16:51:36 CST 2020
     */
    public String getExecuteUserid() {
        return executeUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.execute_userid
     *
     * @param executeUserid the value for task.execute_userid
     *
     * @mbg.generated Mon Sep 07 16:51:36 CST 2020
     */
    public void setExecuteUserid(String executeUserid) {
        this.executeUserid = executeUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.project_id
     *
     * @return the value of task.project_id
     *
     * @mbg.generated Mon Sep 07 16:51:36 CST 2020
     */
    public Long getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.project_id
     *
     * @param projectId the value for task.project_id
     *
     * @mbg.generated Mon Sep 07 16:51:36 CST 2020
     */
    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.begin
     *
     * @return the value of task.begin
     *
     * @mbg.generated Mon Sep 07 16:51:36 CST 2020
     */
    public Date getBegin() {
        return begin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.begin
     *
     * @param begin the value for task.begin
     *
     * @mbg.generated Mon Sep 07 16:51:36 CST 2020
     */
    public void setBegin(Date begin) {
        this.begin = begin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.end
     *
     * @return the value of task.end
     *
     * @mbg.generated Mon Sep 07 16:51:36 CST 2020
     */
    public Date getEnd() {
        return end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.end
     *
     * @param end the value for task.end
     *
     * @mbg.generated Mon Sep 07 16:51:36 CST 2020
     */
    public void setEnd(Date end) {
        this.end = end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.is_completed
     *
     * @return the value of task.is_completed
     *
     * @mbg.generated Mon Sep 07 16:51:36 CST 2020
     */
    public Integer getIsCompleted() {
        return isCompleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.is_completed
     *
     * @param isCompleted the value for task.is_completed
     *
     * @mbg.generated Mon Sep 07 16:51:36 CST 2020
     */
    public void setIsCompleted(Integer isCompleted) {
        this.isCompleted = isCompleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.status
     *
     * @return the value of task.status
     *
     * @mbg.generated Mon Sep 07 16:51:36 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.status
     *
     * @param status the value for task.status
     *
     * @mbg.generated Mon Sep 07 16:51:36 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.remark
     *
     * @return the value of task.remark
     *
     * @mbg.generated Mon Sep 07 16:51:36 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.remark
     *
     * @param remark the value for task.remark
     *
     * @mbg.generated Mon Sep 07 16:51:36 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.station
     *
     * @return the value of task.station
     *
     * @mbg.generated Mon Sep 07 16:51:36 CST 2020
     */
    public String getStation() {
        return station;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.station
     *
     * @param station the value for task.station
     *
     * @mbg.generated Mon Sep 07 16:51:36 CST 2020
     */
    public void setStation(String station) {
        this.station = station;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.is_del
     *
     * @return the value of task.is_del
     *
     * @mbg.generated Mon Sep 07 16:51:36 CST 2020
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.is_del
     *
     * @param isDel the value for task.is_del
     *
     * @mbg.generated Mon Sep 07 16:51:36 CST 2020
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.create_time
     *
     * @return the value of task.create_time
     *
     * @mbg.generated Mon Sep 07 16:51:36 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.create_time
     *
     * @param createTime the value for task.create_time
     *
     * @mbg.generated Mon Sep 07 16:51:36 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.update_time
     *
     * @return the value of task.update_time
     *
     * @mbg.generated Mon Sep 07 16:51:36 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.update_time
     *
     * @param updateTime the value for task.update_time
     *
     * @mbg.generated Mon Sep 07 16:51:36 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.over_days
     *
     * @return the value of task.over_days
     *
     * @mbg.generated Mon Sep 07 16:51:36 CST 2020
     */
    public Integer getOverDays() {
        return overDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.over_days
     *
     * @param overDays the value for task.over_days
     *
     * @mbg.generated Mon Sep 07 16:51:36 CST 2020
     */
    public void setOverDays(Integer overDays) {
        this.overDays = overDays;
    }
}