package com.echair.project_manage.dao.model;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_user.userid
     *
     * @mbg.generated Sat Aug 29 17:38:26 CST 2020
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_user.username
     *
     * @mbg.generated Sat Aug 29 17:38:26 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_user.role_id
     *
     * @mbg.generated Sat Aug 29 17:38:26 CST 2020
     */
    private Long roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_user.status
     *
     * @mbg.generated Sat Aug 29 17:38:26 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_user.avater
     *
     * @mbg.generated Sat Aug 29 17:38:26 CST 2020
     */
    private String avater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_user.name
     *
     * @mbg.generated Sat Aug 29 17:38:26 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_user.is_del
     *
     * @mbg.generated Sat Aug 29 17:38:26 CST 2020
     */
    private Integer isDel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_user.create_time
     *
     * @mbg.generated Sat Aug 29 17:38:26 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_user.update_time
     *
     * @mbg.generated Sat Aug 29 17:38:26 CST 2020
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_user.password
     *
     * @mbg.generated Sat Aug 29 17:38:26 CST 2020
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_user.userid
     *
     * @return the value of pm_user.userid
     *
     * @mbg.generated Sat Aug 29 17:38:26 CST 2020
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_user.userid
     *
     * @param userid the value for pm_user.userid
     *
     * @mbg.generated Sat Aug 29 17:38:26 CST 2020
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_user.username
     *
     * @return the value of pm_user.username
     *
     * @mbg.generated Sat Aug 29 17:38:26 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_user.username
     *
     * @param username the value for pm_user.username
     *
     * @mbg.generated Sat Aug 29 17:38:26 CST 2020
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_user.role_id
     *
     * @return the value of pm_user.role_id
     *
     * @mbg.generated Sat Aug 29 17:38:26 CST 2020
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_user.role_id
     *
     * @param roleId the value for pm_user.role_id
     *
     * @mbg.generated Sat Aug 29 17:38:26 CST 2020
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_user.status
     *
     * @return the value of pm_user.status
     *
     * @mbg.generated Sat Aug 29 17:38:26 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_user.status
     *
     * @param status the value for pm_user.status
     *
     * @mbg.generated Sat Aug 29 17:38:26 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_user.avater
     *
     * @return the value of pm_user.avater
     *
     * @mbg.generated Sat Aug 29 17:38:26 CST 2020
     */
    public String getAvater() {
        return avater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_user.avater
     *
     * @param avater the value for pm_user.avater
     *
     * @mbg.generated Sat Aug 29 17:38:26 CST 2020
     */
    public void setAvater(String avater) {
        this.avater = avater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_user.name
     *
     * @return the value of pm_user.name
     *
     * @mbg.generated Sat Aug 29 17:38:26 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_user.name
     *
     * @param name the value for pm_user.name
     *
     * @mbg.generated Sat Aug 29 17:38:26 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_user.is_del
     *
     * @return the value of pm_user.is_del
     *
     * @mbg.generated Sat Aug 29 17:38:26 CST 2020
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_user.is_del
     *
     * @param isDel the value for pm_user.is_del
     *
     * @mbg.generated Sat Aug 29 17:38:26 CST 2020
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_user.create_time
     *
     * @return the value of pm_user.create_time
     *
     * @mbg.generated Sat Aug 29 17:38:26 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_user.create_time
     *
     * @param createTime the value for pm_user.create_time
     *
     * @mbg.generated Sat Aug 29 17:38:26 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_user.update_time
     *
     * @return the value of pm_user.update_time
     *
     * @mbg.generated Sat Aug 29 17:38:26 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_user.update_time
     *
     * @param updateTime the value for pm_user.update_time
     *
     * @mbg.generated Sat Aug 29 17:38:26 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_user.password
     *
     * @return the value of pm_user.password
     *
     * @mbg.generated Sat Aug 29 17:38:26 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_user.password
     *
     * @param password the value for pm_user.password
     *
     * @mbg.generated Sat Aug 29 17:38:26 CST 2020
     */
    public void setPassword(String password) {
        this.password = password;
    }
}