package com.echair.project_manage.dao.model;

import java.util.Date;

public class Version {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version.id
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version.vaersion
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    private String vaersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version.is_del
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    private Integer isDel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version.create_time
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version.update_time
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version.id
     *
     * @return the value of version.id
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version.id
     *
     * @param id the value for version.id
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version.vaersion
     *
     * @return the value of version.vaersion
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    public String getVaersion() {
        return vaersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version.vaersion
     *
     * @param vaersion the value for version.vaersion
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    public void setVaersion(String vaersion) {
        this.vaersion = vaersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version.is_del
     *
     * @return the value of version.is_del
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version.is_del
     *
     * @param isDel the value for version.is_del
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version.create_time
     *
     * @return the value of version.create_time
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version.create_time
     *
     * @param createTime the value for version.create_time
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version.update_time
     *
     * @return the value of version.update_time
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version.update_time
     *
     * @param updateTime the value for version.update_time
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}