package com.echair.project_manage.dao.mapper;

import com.echair.project_manage.dao.model.Alpha;
import com.echair.project_manage.dao.model.AlphaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AlphaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_alpha
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    long countByExample(AlphaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_alpha
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    int deleteByExample(AlphaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_alpha
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_alpha
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    int insert(Alpha record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_alpha
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    int insertSelective(Alpha record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_alpha
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    List<Alpha> selectByExample(AlphaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_alpha
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    Alpha selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_alpha
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    int updateByExampleSelective(@Param("record") Alpha record, @Param("example") AlphaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_alpha
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    int updateByExample(@Param("record") Alpha record, @Param("example") AlphaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_alpha
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    int updateByPrimaryKeySelective(Alpha record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_alpha
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    int updateByPrimaryKey(Alpha record);
}