package com.echair.project_manage.dao.mapper;

import com.echair.project_manage.dao.model.Aplha;
import com.echair.project_manage.dao.model.AplhaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AplhaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_alpha
     *
     * @mbg.generated Thu Sep 24 15:13:43 CST 2020
     */
    long countByExample(AplhaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_alpha
     *
     * @mbg.generated Thu Sep 24 15:13:43 CST 2020
     */
    int deleteByExample(AplhaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_alpha
     *
     * @mbg.generated Thu Sep 24 15:13:43 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_alpha
     *
     * @mbg.generated Thu Sep 24 15:13:43 CST 2020
     */
    int insert(Aplha record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_alpha
     *
     * @mbg.generated Thu Sep 24 15:13:43 CST 2020
     */
    int insertSelective(Aplha record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_alpha
     *
     * @mbg.generated Thu Sep 24 15:13:43 CST 2020
     */
    List<Aplha> selectByExample(AplhaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_alpha
     *
     * @mbg.generated Thu Sep 24 15:13:43 CST 2020
     */
    Aplha selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_alpha
     *
     * @mbg.generated Thu Sep 24 15:13:43 CST 2020
     */
    int updateByExampleSelective(@Param("record") Aplha record, @Param("example") AplhaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_alpha
     *
     * @mbg.generated Thu Sep 24 15:13:43 CST 2020
     */
    int updateByExample(@Param("record") Aplha record, @Param("example") AplhaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_alpha
     *
     * @mbg.generated Thu Sep 24 15:13:43 CST 2020
     */
    int updateByPrimaryKeySelective(Aplha record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_alpha
     *
     * @mbg.generated Thu Sep 24 15:13:43 CST 2020
     */
    int updateByPrimaryKey(Aplha record);
}