package com.echair.project_manage.dao.mapper;

import com.echair.project_manage.dao.model.AssessRole;
import com.echair.project_manage.dao.model.AssessRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AssessRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assess_role
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    long countByExample(AssessRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assess_role
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    int deleteByExample(AssessRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assess_role
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assess_role
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    int insert(AssessRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assess_role
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    int insertSelective(AssessRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assess_role
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    List<AssessRole> selectByExample(AssessRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assess_role
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    AssessRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assess_role
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    int updateByExampleSelective(@Param("record") AssessRole record, @Param("example") AssessRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assess_role
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    int updateByExample(@Param("record") AssessRole record, @Param("example") AssessRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assess_role
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    int updateByPrimaryKeySelective(AssessRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assess_role
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    int updateByPrimaryKey(AssessRole record);
}