package com.echair.project_manage.dao.mapper;

import com.echair.project_manage.dao.model.Beta;
import com.echair.project_manage.dao.model.BetaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BetaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_beta
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    long countByExample(BetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_beta
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    int deleteByExample(BetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_beta
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_beta
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    int insert(Beta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_beta
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    int insertSelective(Beta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_beta
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    List<Beta> selectByExample(BetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_beta
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    Beta selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_beta
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    int updateByExampleSelective(@Param("record") Beta record, @Param("example") BetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_beta
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    int updateByExample(@Param("record") Beta record, @Param("example") BetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_beta
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    int updateByPrimaryKeySelective(Beta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_beta
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    int updateByPrimaryKey(Beta record);
}