package com.echair.project_manage.dao.mapper;

import com.echair.project_manage.dao.model.Master;
import com.echair.project_manage.dao.model.MasterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MasterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_master
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    long countByExample(MasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_master
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    int deleteByExample(MasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_master
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_master
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    int insert(Master record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_master
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    int insertSelective(Master record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_master
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    List<Master> selectByExample(MasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_master
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    Master selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_master
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    int updateByExampleSelective(@Param("record") Master record, @Param("example") MasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_master
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    int updateByExample(@Param("record") Master record, @Param("example") MasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_master
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    int updateByPrimaryKeySelective(Master record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_master
     *
     * @mbg.generated Thu Sep 24 15:15:01 CST 2020
     */
    int updateByPrimaryKey(Master record);
}