package com.echair.project_manage.dao.mapper;

import com.echair.project_manage.common.pojo.vo.MessageVO;
import com.echair.project_manage.common.pojo.vo.ProjectTaskVO;
import com.echair.project_manage.common.pojo.vo.TaskVO;
import com.echair.project_manage.common.pojo.vo.UserProjectVO;
import com.echair.project_manage.dao.model.Task;
import com.echair.project_manage.dao.model.TaskExample;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated Mon Sep 07 16:51:36 CST 2020
     */
    long countByExample(TaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated Mon Sep 07 16:51:36 CST 2020
     */
    int deleteByExample(TaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated Mon Sep 07 16:51:36 CST 2020
     */
    int deleteByPrimaryKey(Long taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated Mon Sep 07 16:51:36 CST 2020
     */
    int insert(Task record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated Mon Sep 07 16:51:36 CST 2020
     */
    int insertSelective(Task record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated Mon Sep 07 16:51:36 CST 2020
     */
    List<Task> selectByExample(TaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated Mon Sep 07 16:51:36 CST 2020
     */
    Task selectByPrimaryKey(Long taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated Mon Sep 07 16:51:36 CST 2020
     */
    int updateByExampleSelective(@Param("record") Task record, @Param("example") TaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated Mon Sep 07 16:51:36 CST 2020
     */
    int updateByExample(@Param("record") Task record, @Param("example") TaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated Mon Sep 07 16:51:36 CST 2020
     */
    int updateByPrimaryKeySelective(Task record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated Mon Sep 07 16:51:36 CST 2020
     */
    int updateByPrimaryKey(Task record);


    List<UserProjectVO> getTaskProjectList(@Param("userid") String userid, @Param("begin") Date begin, @Param("end") Date end);

    List<TaskVO> getUserTaskList(@Param("userid") String userid,@Param("projectId") long projectId,@Param("begin") Date begin, @Param("end") Date end);

    MessageVO getLatestMessage(@Param("projectId")long projectId);

    ProjectTaskVO getProjectTask(@Param("projectId") long projectId);

}