package com.echair.project_manage.dao.mapper;

import com.echair.project_manage.common.pojo.dto.UserAddDTO;
import com.echair.project_manage.common.pojo.vo.AssessVO;
import com.echair.project_manage.common.pojo.vo.UserVO;
import com.echair.project_manage.dao.model.User;
import com.echair.project_manage.dao.model.UserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_user
     *
     * @mbg.generated Sat Aug 29 17:38:26 CST 2020
     */
    long countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_user
     *
     * @mbg.generated Sat Aug 29 17:38:26 CST 2020
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_user
     *
     * @mbg.generated Sat Aug 29 17:38:26 CST 2020
     */
    int deleteByPrimaryKey(String userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_user
     *
     * @mbg.generated Sat Aug 29 17:38:26 CST 2020
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_user
     *
     * @mbg.generated Sat Aug 29 17:38:26 CST 2020
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_user
     *
     * @mbg.generated Sat Aug 29 17:38:26 CST 2020
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_user
     *
     * @mbg.generated Sat Aug 29 17:38:26 CST 2020
     */
    User selectByPrimaryKey(String userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_user
     *
     * @mbg.generated Sat Aug 29 17:38:26 CST 2020
     */
    int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_user
     *
     * @mbg.generated Sat Aug 29 17:38:26 CST 2020
     */
    int updateByExample(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_user
     *
     * @mbg.generated Sat Aug 29 17:38:26 CST 2020
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_user
     *
     * @mbg.generated Sat Aug 29 17:38:26 CST 2020
     */
    int updateByPrimaryKey(User record);

    UserVO getUser(@Param("username") String username);

    UserVO getUser1(@Param("userid") String userid);

    List<AssessVO> getAssess(@Param("username") String username);

}