package com.echair.project_manage.dao.mapper;

import com.echair.project_manage.dao.model.VersionBeta;
import com.echair.project_manage.dao.model.VersionBetaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VersionBetaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_beta
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    long countByExample(VersionBetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_beta
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    int deleteByExample(VersionBetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_beta
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_beta
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    int insert(VersionBeta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_beta
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    int insertSelective(VersionBeta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_beta
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    List<VersionBeta> selectByExample(VersionBetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_beta
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    VersionBeta selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_beta
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    int updateByExampleSelective(@Param("record") VersionBeta record, @Param("example") VersionBetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_beta
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    int updateByExample(@Param("record") VersionBeta record, @Param("example") VersionBetaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_beta
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    int updateByPrimaryKeySelective(VersionBeta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_beta
     *
     * @mbg.generated Sat Aug 29 17:19:55 CST 2020
     */
    int updateByPrimaryKey(VersionBeta record);
}